# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resize.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 654)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setKerning(False)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color:lightgrey;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background-color:lightgrey;")
        self.home.setObjectName("home")
        self.gridLayout = QtWidgets.QGridLayout(self.home)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.home)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 3)
        self.join = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(14)
        self.join.setFont(font)
        self.join.setStyleSheet("border-radius: 20;  background-color:black; color: orange;")
        self.join.setObjectName("join")
        self.gridLayout.addWidget(self.join, 1, 0, 1, 1)
        self.single = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(14)
        self.single.setFont(font)
        self.single.setStyleSheet("border-radius: 20;  background-color:black; color: orange;")
        self.single.setObjectName("single")
        self.gridLayout.addWidget(self.single, 1, 1, 1, 1)
        self.create = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(14)
        self.create.setFont(font)
        self.create.setStyleSheet("border-radius: 20;  background-color:black; color: orange;")
        self.create.setObjectName("create")
        self.gridLayout.addWidget(self.create, 1, 2, 1, 1)
        self.how = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(14)
        self.how.setFont(font)
        self.how.setStyleSheet("border-radius: 20;  background-color:black; color: orange;")
        self.how.setObjectName("how")
        self.gridLayout.addWidget(self.how, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.home)
        self.multi_game = QtWidgets.QWidget()
        self.multi_game.setMaximumSize(QtCore.QSize(16777215, 400))
        self.multi_game.setObjectName("multi_game")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.multi_game)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(self.multi_game)
        self.label_13.setStyleSheet("background-color:black; border-radius:20;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.multi_game)
        self.label_12.setStyleSheet("background-color:black; border-radius:20;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.multi_game)
        self.create_game = QtWidgets.QWidget()
        self.create_game.setStyleSheet("background-color: lightgrey;")
        self.create_game.setObjectName("create_game")
        self.label_3 = QtWidgets.QLabel(self.create_game)
        self.label_3.setGeometry(QtCore.QRect(280, 190, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.create_game)
        self.pushButton.setGeometry(QtCore.QRect(790, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:red; border-radius:10;")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.create_game)
        self.label_6.setGeometry(QtCore.QRect(340, 260, 131, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.create_game)
        self.label_7.setGeometry(QtCore.QRect(290, 300, 231, 51))
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:black; color: orange; border-radius: 20;")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.create_game)
        self.join_game = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        self.join_game.setFont(font)
        self.join_game.setStyleSheet("background-color: lightgrey; border-radius:20;")
        self.join_game.setObjectName("join_game")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.join_game)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.join_game)
        self.pushButton_2.setMaximumSize(QtCore.QSize(140, 140))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background-color:red; border-radius:10;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.join_game)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.join_game)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("border-radius: 20; background-color:black; color: orange;")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.join_game)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.rooms = QtWidgets.QListWidget(self.join_game)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rooms.setFont(font)
        self.rooms.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rooms.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.rooms.setAcceptDrops(False)
        self.rooms.setAutoFillBackground(False)
        self.rooms.setStyleSheet("background-color:black; color:orange;\n"
"font: 75 19pt \"UnYetgul\";\n"
"text-align: center;")
        self.rooms.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rooms.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rooms.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.rooms.setTextElideMode(QtCore.Qt.ElideNone)
        self.rooms.setFlow(QtWidgets.QListView.TopToBottom)
        self.rooms.setProperty("isWrapping", False)
        self.rooms.setResizeMode(QtWidgets.QListView.Adjust)
        self.rooms.setViewMode(QtWidgets.QListView.ListMode)
        self.rooms.setWordWrap(False)
        self.rooms.setItemAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignJustify)
        self.rooms.setObjectName("rooms")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(19)
        item.setFont(font)
        self.rooms.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("UnYetgul")
        font.setPointSize(19)
        item.setFont(font)
        self.rooms.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.rooms.addItem(item)
        self.gridLayout_5.addWidget(self.rooms, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.join_game)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.join_game)
        self.single_game = QtWidgets.QWidget()
        self.single_game.setStyleSheet("background-color: lightgrey;")
        self.single_game.setObjectName("single_game")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.single_game)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.single_game)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.single_game)
        self.pushButton_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:red; border-radius:10;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.single_game)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label_10.setStyleSheet("background-color:black; border-radius:20;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.single_game)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label_11.setStyleSheet("background-color:black; border-radius:20;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.single_game)
        self.how_to = QtWidgets.QWidget()
        self.how_to.setStyleSheet("background-color:lightgrey;")
        self.how_to.setObjectName("how_to")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.how_to)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.how_to)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("background-color:black; color:orange; border-radius:20;")
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.how_to)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_4.setStyleSheet("background-color:red; border-radius:10;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.how_to)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"logo.png\"/></p></body></html>"))
        self.join.setText(_translate("MainWindow", "Join a room"))
        self.single.setText(_translate("MainWindow", "Singleplayer"))
        self.create.setText(_translate("MainWindow", "Create a room"))
        self.how.setText(_translate("MainWindow", "How to play"))
        self.label_3.setText(_translate("MainWindow", "Create a game"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "your game code is:"))
        self.pushButton_2.setText(_translate("MainWindow", "X"))
        self.label_5.setText(_translate("MainWindow", "enter the game code"))
        self.label_8.setText(_translate("MainWindow", "Or join an available room"))
        self.rooms.setSortingEnabled(True)
        __sortingEnabled = self.rooms.isSortingEnabled()
        self.rooms.setSortingEnabled(False)
        item = self.rooms.item(0)
        item.setText(_translate("MainWindow", "Room 1"))
        item = self.rooms.item(1)
        item.setText(_translate("MainWindow", "Room 2"))
        item = self.rooms.item(2)
        item.setText(_translate("MainWindow", "Room 3"))
        self.rooms.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Join a Game"))
        self.label.setText(_translate("MainWindow", "Single Player"))
        self.pushButton_3.setText(_translate("MainWindow", "X"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">How to play</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:12pt;\">The game is played by placing your hand in front of your webcam</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Games consist of 5 round. Whoever wins the most rounds is the overal winner</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:12pt;\">You can play against other players online or against an AI</span></p><p align=\"center\"><span style=\" font-size:12pt;\">(Moet nog uitgebreid/verbeterd worden)</span></p><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "X"))

